{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "ab85a31f-a1f7-47b1-bcc2-e34fe3b52f04",
   "metadata": {},
   "source": [
    "# Train the RNN style metric model (NSynth)\n",
    "\n",
    "Contrastively, using bilinear similarity"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "68fb27b3-4c3b-43a8-a312-ffe31d13f0ae",
   "metadata": {},
   "source": [
    "## Setup"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "1ad730ae-a96e-45e5-8b15-059e8fcbf7fc",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2024-07-12 19:09:54.751485: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.\n",
      "To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.\n",
      "2024-07-12 19:09:56.532046: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT\n"
     ]
    }
   ],
   "source": [
    "from ss_vq_vae.models.vqvae_oneshot import Model\n",
    "import confugue"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "96846605-f076-4b46-ab8e-50e798b35e6a",
   "metadata": {},
   "outputs": [],
   "source": [
    "cfg_path = \"/mnt/vdb/model-original-no-style-pretraining-19-11-2023/config.yaml\"\n",
    "cfg = confugue.Configuration.from_yaml_file(cfg_path)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "ced5b726-804b-4c1f-b58a-7d67f77ba7f2",
   "metadata": {},
   "outputs": [],
   "source": [
    "from ss_vq_vae.nn.nn import ResidualWrapper\n",
    "from ss_vq_vae.nn.bilinear_similarity import BilinearSimilarity\n",
    "from torch import nn\n",
    "\n",
    "class StyleEncoder(nn.Module):\n",
    "    def __init__(self, cfg):\n",
    "        super().__init__()\n",
    "        self.style_encoder_1d = nn.Sequential(*cfg['model']['style_encoder_1d'].configure_list())\n",
    "        self.style_encoder_rnn = cfg['model']['style_encoder_rnn'].maybe_configure(nn.GRU, batch_first=True)\n",
    "        self.style_encoder_0d = nn.Sequential(*cfg['model']['style_encoder_0d'].configure_list())\n",
    "        \n",
    "    def forward(self, input, length):\n",
    "        encoded = self.style_encoder_1d(input)\n",
    "\n",
    "        # Mask positions corresponding to padding\n",
    "        length = (length // (input.shape[2] / encoded.shape[2])).to(torch.int)\n",
    "        mask = (torch.arange(encoded.shape[2], device=encoded.device) < length[:, None])[:, None, :]\n",
    "        encoded = encoded * mask\n",
    "\n",
    "        if self.style_encoder_rnn is not None:\n",
    "            encoded = encoded.transpose(1, 2)\n",
    "            encoded = nn.utils.rnn.pack_padded_sequence(\n",
    "                encoded, length.clamp(min=1).to('cpu'),\n",
    "                batch_first=True, enforce_sorted=False)\n",
    "            _, encoded = self.style_encoder_rnn(encoded)\n",
    "            # Get rid of layer dimension\n",
    "            encoded = encoded.transpose(0, 1).reshape(input.shape[0], -1)\n",
    "        else:\n",
    "            # Compute the Gram matrix, normalized by the length squared\n",
    "            encoded = encoded / mask.sum(dim=2, keepdim=True) + torch.finfo(encoded.dtype).eps\n",
    "            encoded = torch.matmul(encoded, encoded.transpose(1, 2))\n",
    "        encoded = encoded.reshape(encoded.shape[0], -1)\n",
    "\n",
    "        encoded = self.style_encoder_0d(encoded)\n",
    "\n",
    "        return encoded, {}\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "id": "4710a244-b99d-484a-8c01-1b7d1f23990d",
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "import json\n",
    "import torch\n",
    "from torch.utils.data import Dataset, DataLoader\n",
    "import librosa\n",
    "import numpy as np\n",
    "\n",
    "class NSynthDataset(Dataset):\n",
    "    def __init__(self, cfg, base_folder, json_file='examples.json', sampling_rate=16_000):\n",
    "        self.base_folder = base_folder\n",
    "        self.json_file = json_file\n",
    "        self.data = self._load_metadata()\n",
    "        self.instrument_to_samples = self._group_by_instrument()\n",
    "        self.sr = sampling_rate\n",
    "        self.spec_fn = cfg['spectrogram'].bind(librosa.stft)\n",
    "\n",
    "    def _load_metadata(self):\n",
    "        with open(os.path.join(self.base_folder, self.json_file), 'r') as f:\n",
    "            data = json.load(f)\n",
    "        return data\n",
    "    \n",
    "    def preprocess_audio(self, audio_path):\n",
    "        audio, _ = librosa.load(audio_path, sr=self.sr)\n",
    "        if len(audio) == 0:\n",
    "            audio = np.zeros(shape=[1], dtype=audio.dtype)\n",
    "        return np.log1p(np.abs(self.spec_fn(y=audio)))\n",
    "\n",
    "    def _group_by_instrument(self):\n",
    "        instrument_to_samples = {}\n",
    "        for key, value in self.data.items():\n",
    "            instrument = value['instrument']\n",
    "            if instrument not in instrument_to_samples:\n",
    "                instrument_to_samples[instrument] = []\n",
    "            instrument_to_samples[instrument].append(key)\n",
    "        return instrument_to_samples\n",
    "\n",
    "    def __len__(self):\n",
    "        return len(self.data)\n",
    "\n",
    "    def __getitem__(self, idx):\n",
    "        key = list(self.data.keys())[idx]\n",
    "        audio_path = os.path.join(self.base_folder, 'audio', f\"{key}.wav\")\n",
    "        waveform = self.preprocess_audio(audio_path)\n",
    "        sample = self.data[key]\n",
    "        return waveform"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 32,
   "id": "72b711d7-ffc9-4e74-b02a-f2e16bb5e89f",
   "metadata": {},
   "outputs": [],
   "source": [
    "from torch.utils.data import Sampler\n",
    "import random\n",
    "\n",
    "class PairSampler(Sampler):\n",
    "    def __init__(self, dataset, batch_size):\n",
    "        self.dataset = dataset\n",
    "        self.batch_size = batch_size\n",
    "        self.instrument_to_indices = self._group_indices_by_instrument()\n",
    "\n",
    "    def _group_indices_by_instrument(self):\n",
    "        instrument_to_indices = {}\n",
    "        for idx, sample in enumerate(self.dataset.data.values()):\n",
    "            instrument = sample['instrument']\n",
    "            if instrument not in instrument_to_indices:\n",
    "                instrument_to_indices[instrument] = []\n",
    "            instrument_to_indices[instrument].append(idx)\n",
    "        return instrument_to_indices\n",
    "\n",
    "    def __iter__(self):\n",
    "        instruments = list(self.instrument_to_indices.keys())\n",
    "        random.shuffle(instruments)\n",
    "        batch = []\n",
    "        no_of_batches = 0\n",
    "        \n",
    "        while True:\n",
    "            for instrument in instruments:\n",
    "                if no_of_batches == len(self):\n",
    "                    return\n",
    "                indices = self.instrument_to_indices[instrument]\n",
    "                if len(indices) < 2:\n",
    "                    continue  # Skip instruments that don't have at least 2 samples\n",
    "                random.shuffle(indices)\n",
    "                pair = indices[:2]\n",
    "                batch.extend(pair)\n",
    "                if len(batch) == 2 * self.batch_size:\n",
    "                    yield batch\n",
    "                    no_of_batches += 1\n",
    "                    batch = []\n",
    "            if batch:\n",
    "                yield batch\n",
    "                no_of_batches += 1\n",
    "                batch = []\n",
    "\n",
    "    def __len__(self):\n",
    "        return len(self.dataset) // (2 * self.batch_size)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "88524eee-5fdc-41da-9e86-a98d28654f2a",
   "metadata": {},
   "source": [
    "### Training loop"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 33,
   "id": "dac8c08f-6833-4efe-b79c-67979cca11b7",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "StyleEncoder(\n",
       "  (style_encoder_1d): Sequential(\n",
       "    (0): Conv1d(1025, 1024, kernel_size=(4,), stride=(2,))\n",
       "    (1): ResidualWrapper(\n",
       "      (module): Sequential(\n",
       "        (0): BatchNorm1d(1024, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)\n",
       "        (1): LeakyReLU(negative_slope=0.1)\n",
       "        (2): Conv1d(1024, 1024, kernel_size=(1,), stride=(1,))\n",
       "      )\n",
       "    )\n",
       "    (2): BatchNorm1d(1024, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)\n",
       "    (3): LeakyReLU(negative_slope=0.1)\n",
       "  )\n",
       "  (style_encoder_rnn): GRU(1024, 1024, batch_first=True)\n",
       "  (style_encoder_0d): Sequential()\n",
       ")"
      ]
     },
     "execution_count": 33,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "style_encoder = StyleEncoder(cfg)\n",
    "style_encoder"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 34,
   "id": "1c40b70c-deb1-4ddb-9db3-5bd3aa08a21b",
   "metadata": {},
   "outputs": [],
   "source": [
    "train_audios_folder = \"/mnt/vdc/nsynth-train/\"\n",
    "valid_audios_folder = \"/mnt/vdc/nsynth-valid/\"\n",
    "output_path = \"/mnt/vdc/run-contrastive-original-style-metric-nsynth-12-07-2024\"\n",
    "\n",
    "batch_size = 64\n",
    "learning_rate = 0.001\n",
    "no_of_epochs = 500\n",
    "# TODO: dodaj poniÅ¼ej config device\n",
    "device = 'cuda'"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 35,
   "id": "f585d9f4-a4d3-47d1-ba04-df51d7e4d958",
   "metadata": {
    "tags": []
   },
   "outputs": [
    {
     "data": {
      "text/html": [
       "Finishing last run (ID:fvru22xt) before initializing another..."
      ],
      "text/plain": [
       "<IPython.core.display.HTML object>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "text/html": [
       "Waiting for W&B process to finish... <strong style=\"color:green\">(success).</strong>"
      ],
      "text/plain": [
       "<IPython.core.display.HTML object>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "b2a70e0541264f04bdf673e379011496",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "VBox(children=(Label(value='0.002 MB of 0.007 MB uploaded (0.000 MB deduped)\\r'), FloatProgress(value=0.286193â¦"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "text/html": [
       "<style>\n",
       "    table.wandb td:nth-child(1) { padding: 0 10px; text-align: left ; width: auto;} td:nth-child(2) {text-align: left ; width: 100%}\n",
       "    .wandb-row { display: flex; flex-direction: row; flex-wrap: wrap; justify-content: flex-start; width: 100% }\n",
       "    .wandb-col { display: flex; flex-direction: column; flex-basis: 100%; flex: 1; padding: 10px; }\n",
       "    </style>\n",
       "<div class=\"wandb-row\"><div class=\"wandb-col\"><h3>Run history:</h3><br/><table class=\"wandb\"><tr><td>train_loss</td><td>ââââââââââââââââââââââââââââââââââââââââ</td></tr></table><br/></div><div class=\"wandb-col\"><h3>Run summary:</h3><br/><table class=\"wandb\"><tr><td>train_loss</td><td>4.84941</td></tr></table><br/></div></div>"
      ],
      "text/plain": [
       "<IPython.core.display.HTML object>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "text/html": [
       " View run <strong style=\"color:#cdcd00\">dulcet-moon-13</strong> at: <a href='https://wandb.ai/wojtekk23/original_style_metric_training_nsynth/runs/fvru22xt' target=\"_blank\">https://wandb.ai/wojtekk23/original_style_metric_training_nsynth/runs/fvru22xt</a><br/>Synced 6 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)"
      ],
      "text/plain": [
       "<IPython.core.display.HTML object>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "text/html": [
       "Find logs at: <code>./wandb/run-20240712_193221-fvru22xt/logs</code>"
      ],
      "text/plain": [
       "<IPython.core.display.HTML object>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "text/html": [
       "Successfully finished last run (ID:fvru22xt). Initializing new run:<br/>"
      ],
      "text/plain": [
       "<IPython.core.display.HTML object>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "c112805f9e814ae4921ff95802d1bcc4",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "VBox(children=(Label(value='Waiting for wandb.init()...\\r'), FloatProgress(value=0.016669640566669842, max=1.0â¦"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "text/html": [
       "wandb version 0.17.4 is available!  To upgrade, please run:\n",
       " $ pip install wandb --upgrade"
      ],
      "text/plain": [
       "<IPython.core.display.HTML object>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "text/html": [
       "Tracking run with wandb version 0.15.5"
      ],
      "text/plain": [
       "<IPython.core.display.HTML object>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "text/html": [
       "Run data is saved locally in <code>/home/user/ss-vq-vae/experiments/rnn_style_metric/wandb/run-20240712_194609-t9deyn6d</code>"
      ],
      "text/plain": [
       "<IPython.core.display.HTML object>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "text/html": [
       "Syncing run <strong><a href='https://wandb.ai/wojtekk23/original_style_metric_training_nsynth/runs/t9deyn6d' target=\"_blank\">royal-moon-14</a></strong> to <a href='https://wandb.ai/wojtekk23/original_style_metric_training_nsynth' target=\"_blank\">Weights & Biases</a> (<a href='https://wandb.me/run' target=\"_blank\">docs</a>)<br/>"
      ],
      "text/plain": [
       "<IPython.core.display.HTML object>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "text/html": [
       " View project at <a href='https://wandb.ai/wojtekk23/original_style_metric_training_nsynth' target=\"_blank\">https://wandb.ai/wojtekk23/original_style_metric_training_nsynth</a>"
      ],
      "text/plain": [
       "<IPython.core.display.HTML object>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "text/html": [
       " View run at <a href='https://wandb.ai/wojtekk23/original_style_metric_training_nsynth/runs/t9deyn6d' target=\"_blank\">https://wandb.ai/wojtekk23/original_style_metric_training_nsynth/runs/t9deyn6d</a>"
      ],
      "text/plain": [
       "<IPython.core.display.HTML object>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "1000it [06:02,  2.76it/s]\n",
      "Exception ignored in: \n",
      "<function _MultiProcessingDataLoaderIter.__del__ at 0x7f394b22d430>Traceback (most recent call last):\n",
      "  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1478, in __del__\n",
      "    Exception ignored in: self._shutdown_workers()<function _MultiProcessingDataLoaderIter.__del__ at 0x7f394b22d430>\n",
      "\n",
      "0it [00:00, ?it/s]Traceback (most recent call last):\n",
      "  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1461, in _shutdown_workers\n",
      "      File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1478, in __del__\n",
      "if w.is_alive():    \n",
      "  File \"/home/user/miniconda3/lib/python3.8/multiprocessing/process.py\", line 160, in is_alive\n",
      "self._shutdown_workers()Exception ignored in:     Exception ignored in: assert self._parent_pid == os.getpid(), 'can only test a child process'\n",
      "\n",
      "AssertionError<function _MultiProcessingDataLoaderIter.__del__ at 0x7f394b22d430><function _MultiProcessingDataLoaderIter.__del__ at 0x7f394b22d430>  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1461, in _shutdown_workers\n",
      "\n",
      "\n",
      "Traceback (most recent call last):\n",
      ": can only test a child processTraceback (most recent call last):\n",
      "\n",
      "  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1478, in __del__\n",
      "    if w.is_alive():  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1478, in __del__\n",
      "    self._shutdown_workers()\n",
      "  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1461, in _shutdown_workers\n",
      "\n",
      "          File \"/home/user/miniconda3/lib/python3.8/multiprocessing/process.py\", line 160, in is_alive\n",
      "if w.is_alive():\n",
      "self._shutdown_workers()    \n",
      "assert self._parent_pid == os.getpid(), 'can only test a child process'  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1461, in _shutdown_workers\n",
      "    if w.is_alive():\n",
      "AssertionError\n",
      ":   File \"/home/user/miniconda3/lib/python3.8/multiprocessing/process.py\", line 160, in is_alive\n",
      "    can only test a child processassert self._parent_pid == os.getpid(), 'can only test a child process'\n",
      "\n",
      "AssertionError:   File \"/home/user/miniconda3/lib/python3.8/multiprocessing/process.py\", line 160, in is_alive\n",
      "can only test a child process\n",
      "    assert self._parent_pid == os.getpid(), 'can only test a child process'\n",
      "AssertionError: can only test a child process\n",
      "99it [00:23,  4.15it/s]\n",
      "1000it [06:00,  2.77it/s]\n",
      "Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f394b22d430>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1478, in __del__\n",
      "    self._shutdown_workers()\n",
      "  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1461, in _shutdown_workers\n",
      "    if w.is_alive():\n",
      "  File \"/home/user/miniconda3/lib/python3.8/multiprocessing/process.py\", line 160, in is_alive\n",
      "    assert self._parent_pid == os.getpid(), 'can only test a child process'\n",
      "AssertionError: can only test a child process\n",
      "99it [00:18,  5.40it/s]\n",
      "1000it [06:08,  2.71it/s]\n",
      "0it [00:00, ?it/s]Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f394b22d430>Exception ignored in: Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f394b22d430><function _MultiProcessingDataLoaderIter.__del__ at 0x7f394b22d430>\n",
      "Traceback (most recent call last):\n",
      "\n",
      "Traceback (most recent call last):\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1478, in __del__\n",
      "      File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1478, in __del__\n",
      "      File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1478, in __del__\n",
      "self._shutdown_workers()\n",
      "self._shutdown_workers()  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1461, in _shutdown_workers\n",
      "    \n",
      "      File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1461, in _shutdown_workers\n",
      "self._shutdown_workers()if w.is_alive():\n",
      "Exception ignored in:     \n",
      "<function _MultiProcessingDataLoaderIter.__del__ at 0x7f394b22d430>  File \"/home/user/miniconda3/lib/python3.8/multiprocessing/process.py\", line 160, in is_alive\n",
      "  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1461, in _shutdown_workers\n",
      "        if w.is_alive():if w.is_alive():\n",
      "\n",
      "assert self._parent_pid == os.getpid(), 'can only test a child process'  File \"/home/user/miniconda3/lib/python3.8/multiprocessing/process.py\", line 160, in is_alive\n",
      "\n",
      "    \n",
      "  File \"/home/user/miniconda3/lib/python3.8/multiprocessing/process.py\", line 160, in is_alive\n",
      "AssertionErrorTraceback (most recent call last):\n",
      "  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1478, in __del__\n",
      "assert self._parent_pid == os.getpid(), 'can only test a child process'    : \n",
      "    AssertionErrorassert self._parent_pid == os.getpid(), 'can only test a child process'\n",
      ": self._shutdown_workers()can only test a child processAssertionError\n",
      "\n",
      "can only test a child process: can only test a child process\n",
      "  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1461, in _shutdown_workers\n",
      "    \n",
      "if w.is_alive():\n",
      "  File \"/home/user/miniconda3/lib/python3.8/multiprocessing/process.py\", line 160, in is_alive\n",
      "    assert self._parent_pid == os.getpid(), 'can only test a child process'\n",
      "AssertionError: can only test a child process\n",
      "99it [00:23,  4.17it/s]\n",
      "0it [00:00, ?it/s]Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f394b22d430>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1478, in __del__\n",
      "    self._shutdown_workers()\n",
      "  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1461, in _shutdown_workers\n",
      "    if w.is_alive():\n",
      "  File \"/home/user/miniconda3/lib/python3.8/multiprocessing/process.py\", line 160, in is_alive\n",
      "Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f394b22d430>Exception ignored in: \n",
      "<function _MultiProcessingDataLoaderIter.__del__ at 0x7f394b22d430>    Traceback (most recent call last):\n",
      "\n",
      "assert self._parent_pid == os.getpid(), 'can only test a child process'Traceback (most recent call last):\n",
      "\n",
      "AssertionError  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1478, in __del__\n",
      ":   File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1478, in __del__\n",
      "can only test a child process        \n",
      "self._shutdown_workers()self._shutdown_workers()\n",
      "\n",
      "  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1461, in _shutdown_workers\n",
      "  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1461, in _shutdown_workers\n",
      "        if w.is_alive():if w.is_alive():\n",
      "  File \"/home/user/miniconda3/lib/python3.8/multiprocessing/process.py\", line 160, in is_alive\n",
      "\n",
      "      File \"/home/user/miniconda3/lib/python3.8/multiprocessing/process.py\", line 160, in is_alive\n",
      "assert self._parent_pid == os.getpid(), 'can only test a child process'    Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f394b22d430>\n",
      "AssertionErrorassert self._parent_pid == os.getpid(), 'can only test a child process': \n",
      "\n",
      "can only test a child process\n",
      "Traceback (most recent call last):\n",
      "AssertionError  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1478, in __del__\n",
      ": can only test a child process    self._shutdown_workers()\n",
      "\n",
      "  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1461, in _shutdown_workers\n",
      "Exception ignored in:     <function _MultiProcessingDataLoaderIter.__del__ at 0x7f394b22d430>\n",
      "if w.is_alive():Traceback (most recent call last):\n",
      "\n",
      "  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1478, in __del__\n",
      "  File \"/home/user/miniconda3/lib/python3.8/multiprocessing/process.py\", line 160, in is_alive\n",
      "        assert self._parent_pid == os.getpid(), 'can only test a child process'self._shutdown_workers()\n",
      "\n",
      "  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1461, in _shutdown_workers\n",
      "Exception ignored in:     AssertionError<function _MultiProcessingDataLoaderIter.__del__ at 0x7f394b22d430>Exception ignored in: : <function _MultiProcessingDataLoaderIter.__del__ at 0x7f394b22d430>can only test a child process\n",
      "\n",
      "if w.is_alive():\n",
      "\n",
      "Traceback (most recent call last):\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/user/miniconda3/lib/python3.8/multiprocessing/process.py\", line 160, in is_alive\n",
      "  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1478, in __del__\n",
      "          File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1478, in __del__\n",
      "self._shutdown_workers()    assert self._parent_pid == os.getpid(), 'can only test a child process'self._shutdown_workers()\n",
      "\n",
      "  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1461, in _shutdown_workers\n",
      "\n",
      "AssertionError    Exception ignored in:   File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1461, in _shutdown_workers\n",
      ": if w.is_alive():<function _MultiProcessingDataLoaderIter.__del__ at 0x7f394b22d430>\n",
      "    Traceback (most recent call last):\n",
      "\n",
      "can only test a child process  File \"/home/user/miniconda3/lib/python3.8/multiprocessing/process.py\", line 160, in is_alive\n",
      "  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1478, in __del__\n",
      "if w.is_alive():\n",
      "    \n",
      "self._shutdown_workers()    assert self._parent_pid == os.getpid(), 'can only test a child process'  File \"/home/user/miniconda3/lib/python3.8/multiprocessing/process.py\", line 160, in is_alive\n",
      "\n",
      "\n",
      "      File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1461, in _shutdown_workers\n",
      "AssertionError: assert self._parent_pid == os.getpid(), 'can only test a child process'    \n",
      "can only test a child processif w.is_alive():\n",
      "AssertionError\n",
      "  File \"/home/user/miniconda3/lib/python3.8/multiprocessing/process.py\", line 160, in is_alive\n",
      "    : can only test a child processassert self._parent_pid == os.getpid(), 'can only test a child process'\n",
      "\n",
      "AssertionError: can only test a child process\n",
      "1000it [06:04,  2.75it/s]\n",
      "Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f394b22d430>  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1478, in __del__\n",
      "\n",
      "Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f394b22d430>Exception ignored in: Traceback (most recent call last):\n",
      "<function _MultiProcessingDataLoaderIter.__del__ at 0x7f394b22d430>    self._shutdown_workers()\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1478, in __del__\n",
      "\n",
      "    Traceback (most recent call last):\n",
      "self._shutdown_workers()\n",
      "  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1478, in __del__\n",
      "  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1461, in _shutdown_workers\n",
      "    Exception ignored in: \n",
      "  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1461, in _shutdown_workers\n",
      "self._shutdown_workers()\n",
      "  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1461, in _shutdown_workers\n",
      "0it [00:00, ?it/s]s_alive():if w.is_alive():<function _MultiProcessingDataLoaderIter.__del__ at 0x7f394b22d430>if w.is_alive():\n",
      "\n",
      "\n",
      "  File \"/home/user/miniconda3/lib/python3.8/multiprocessing/process.py\", line 160, in is_alive\n",
      "  File \"/home/user/miniconda3/lib/python3.8/multiprocessing/process.py\", line 160, in is_alive\n",
      "Traceback (most recent call last):\n",
      "    assert self._parent_pid == os.getpid(), 'can only test a child process'\n",
      "  File \"/home/user/miniconda3/lib/python3.8/multiprocessing/process.py\", line 160, in is_alive\n",
      "        \n",
      "  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1478, in __del__\n",
      "AssertionError: can only test a child process\n",
      "    assert self._parent_pid == os.getpid(), 'can only test a child process'\n",
      "assert self._parent_pid == os.getpid(), 'can only test a child process'AssertionErrorself._shutdown_workers(): \n",
      "can only test a child process  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1461, in _shutdown_workers\n",
      "\n",
      "\n",
      "    if w.is_alive():AssertionError\n",
      ":   File \"/home/user/miniconda3/lib/python3.8/multiprocessing/process.py\", line 160, in is_alive\n",
      "can only test a child process\n",
      "    assert self._parent_pid == os.getpid(), 'can only test a child process'\n",
      "AssertionError: can only test a child process\n",
      "Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f394b22d430>\n",
      "Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f394b22d430>Traceback (most recent call last):\n",
      "  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1478, in __del__\n",
      "\n",
      "    Traceback (most recent call last):\n",
      "self._shutdown_workers()\n",
      "  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1461, in _shutdown_workers\n",
      "  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1478, in __del__\n",
      "    if w.is_alive():    \n",
      "self._shutdown_workers()  File \"/home/user/miniconda3/lib/python3.8/multiprocessing/process.py\", line 160, in is_alive\n",
      "    assert self._parent_pid == os.getpid(), 'can only test a child process'Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f394b22d430>\n",
      "\n",
      "Traceback (most recent call last):\n",
      "AssertionError  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1478, in __del__\n",
      "\n",
      ":       File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1461, in _shutdown_workers\n",
      "can only test a child processself._shutdown_workers()    if w.is_alive():\n",
      "\n",
      "  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1461, in _shutdown_workers\n",
      "    \n",
      "if w.is_alive():Exception ignored in:   File \"/home/user/miniconda3/lib/python3.8/multiprocessing/process.py\", line 160, in is_alive\n",
      "\n",
      "<function _MultiProcessingDataLoaderIter.__del__ at 0x7f394b22d430>  File \"/home/user/miniconda3/lib/python3.8/multiprocessing/process.py\", line 160, in is_alive\n",
      "\n",
      "    assert self._parent_pid == os.getpid(), 'can only test a child process'Traceback (most recent call last):\n",
      "  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1478, in __del__\n",
      "    \n",
      "    assert self._parent_pid == os.getpid(), 'can only test a child process'self._shutdown_workers()AssertionError: \n",
      "AssertionError\n",
      "  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1461, in _shutdown_workers\n",
      ": can only test a child processcan only test a child process    \n",
      "\n",
      "if w.is_alive():\n",
      "  File \"/home/user/miniconda3/lib/python3.8/multiprocessing/process.py\", line 160, in is_alive\n",
      "    assert self._parent_pid == os.getpid(), 'can only test a child process'\n",
      "AssertionError: can only test a child process\n",
      "99it [00:21,  4.54it/s]\n",
      "0it [00:00, ?it/s]Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f394b22d430>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1478, in __del__\n",
      "    self._shutdown_workers()\n",
      "Exception ignored in:   File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1461, in _shutdown_workers\n",
      "    <function _MultiProcessingDataLoaderIter.__del__ at 0x7f394b22d430>\n",
      "if w.is_alive():Traceback (most recent call last):\n",
      "\n",
      "  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1478, in __del__\n",
      "      File \"/home/user/miniconda3/lib/python3.8/multiprocessing/process.py\", line 160, in is_alive\n",
      "    self._shutdown_workers()assert self._parent_pid == os.getpid(), 'can only test a child process'\n",
      "\n",
      "  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1461, in _shutdown_workers\n",
      "    if w.is_alive():AssertionErrorException ignored in: : <function _MultiProcessingDataLoaderIter.__del__ at 0x7f394b22d430>can only test a child process\n",
      "\n",
      "\n",
      "  File \"/home/user/miniconda3/lib/python3.8/multiprocessing/process.py\", line 160, in is_alive\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1478, in __del__\n",
      "    assert self._parent_pid == os.getpid(), 'can only test a child process'\n",
      "AssertionError    : Exception ignored in: self._shutdown_workers()Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f394b22d430><function _MultiProcessingDataLoaderIter.__del__ at 0x7f394b22d430>\n",
      "can only test a child process\n",
      "\n",
      "  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1461, in _shutdown_workers\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1478, in __del__\n",
      "\n",
      "        Traceback (most recent call last):\n",
      "  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1478, in __del__\n",
      "if w.is_alive():\n",
      "      File \"/home/user/miniconda3/lib/python3.8/multiprocessing/process.py\", line 160, in is_alive\n",
      "Exception ignored in:     self._shutdown_workers()assert self._parent_pid == os.getpid(), 'can only test a child process'<function _MultiProcessingDataLoaderIter.__del__ at 0x7f394b22d430>\n",
      "\n",
      "Exception ignored in: \n",
      "Exception ignored in: self._shutdown_workers()Traceback (most recent call last):\n",
      "  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1461, in _shutdown_workers\n",
      "<function _MultiProcessingDataLoaderIter.__del__ at 0x7f394b22d430>\n",
      "<function _MultiProcessingDataLoaderIter.__del__ at 0x7f394b22d430>\n",
      "  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1478, in __del__\n",
      "  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1461, in _shutdown_workers\n",
      "    \n",
      "    Traceback (most recent call last):\n",
      "AssertionErrorself._shutdown_workers()    \n",
      "Traceback (most recent call last):\n",
      "if w.is_alive():  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1478, in __del__\n",
      ": if w.is_alive():can only test a child process  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1478, in __del__\n",
      "\n",
      "  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1461, in _shutdown_workers\n",
      "\n",
      "  File \"/home/user/miniconda3/lib/python3.8/multiprocessing/process.py\", line 160, in is_alive\n",
      "\n",
      "      File \"/home/user/miniconda3/lib/python3.8/multiprocessing/process.py\", line 160, in is_alive\n",
      "self._shutdown_workers()                assert self._parent_pid == os.getpid(), 'can only test a child process'self._shutdown_workers()assert self._parent_pid == os.getpid(), 'can only test a child process'\n",
      "\n",
      "\n",
      "if w.is_alive():\n",
      "  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1461, in _shutdown_workers\n",
      "    AssertionError\n",
      "if w.is_alive():\n",
      "AssertionError  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1461, in _shutdown_workers\n",
      ":   File \"/home/user/miniconda3/lib/python3.8/multiprocessing/process.py\", line 160, in is_alive\n",
      "      File \"/home/user/miniconda3/lib/python3.8/multiprocessing/process.py\", line 160, in is_alive\n",
      ":     can only test a child process    can only test a child processassert self._parent_pid == os.getpid(), 'can only test a child process'\n",
      "if w.is_alive():\n",
      "assert self._parent_pid == os.getpid(), 'can only test a child process'\n",
      "\n",
      "\n",
      "AssertionError: AssertionError  File \"/home/user/miniconda3/lib/python3.8/multiprocessing/process.py\", line 160, in is_alive\n",
      "can only test a child process:     \n",
      "assert self._parent_pid == os.getpid(), 'can only test a child process'\n",
      "can only test a child process\n",
      "AssertionError: can only test a child process\n",
      "1000it [06:11,  2.69it/s]\n",
      "Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f394b22d430>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1478, in __del__\n",
      "    self._shutdown_workers()\n",
      "  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1461, in _shutdown_workers\n",
      "    if w.is_alive():\n",
      "  File \"/home/user/miniconda3/lib/python3.8/multiprocessing/process.py\", line 160, in is_alive\n",
      "    assert self._parent_pid == os.getpid(), 'can only test a child process'\n",
      "AssertionError: can only test a child process\n",
      "0it [00:00, ?it/s]Exception ignored in: Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f394b22d430><function _MultiProcessingDataLoaderIter.__del__ at 0x7f394b22d430>\n",
      "\n",
      "Traceback (most recent call last):\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1478, in __del__\n",
      "  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1478, in __del__\n",
      "        self._shutdown_workers()\n",
      "self._shutdown_workers()  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1461, in _shutdown_workers\n",
      "\n",
      "Exception ignored in:     <function _MultiProcessingDataLoaderIter.__del__ at 0x7f394b22d430>  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1461, in _shutdown_workers\n",
      "\n",
      "if w.is_alive():\n",
      "    Traceback (most recent call last):\n",
      "if w.is_alive():  File \"/home/user/miniconda3/lib/python3.8/multiprocessing/process.py\", line 160, in is_alive\n",
      "  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1478, in __del__\n",
      "\n",
      "      File \"/home/user/miniconda3/lib/python3.8/multiprocessing/process.py\", line 160, in is_alive\n",
      "assert self._parent_pid == os.getpid(), 'can only test a child process'        assert self._parent_pid == os.getpid(), 'can only test a child process'self._shutdown_workers()\n",
      "\n",
      "\n",
      "AssertionErrorAssertionError  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1461, in _shutdown_workers\n",
      ": : can only test a child process    can only test a child processif w.is_alive():\n",
      "Exception ignored in: \n",
      "\n",
      "  File \"/home/user/miniconda3/lib/python3.8/multiprocessing/process.py\", line 160, in is_alive\n",
      "    <function _MultiProcessingDataLoaderIter.__del__ at 0x7f394b22d430>\n",
      "assert self._parent_pid == os.getpid(), 'can only test a child process'Traceback (most recent call last):\n",
      "\n",
      "  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1478, in __del__\n",
      "AssertionError    self._shutdown_workers()\n",
      ": can only test a child process  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1461, in _shutdown_workers\n",
      "\n",
      "    if w.is_alive():\n",
      "  File \"/home/user/miniconda3/lib/python3.8/multiprocessing/process.py\", line 160, in is_alive\n",
      "    assert self._parent_pid == os.getpid(), 'can only test a child process'\n",
      "AssertionError: can only test a child process\n",
      "99it [00:22,  4.42it/s]\n",
      "0it [00:00, ?it/s]Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f394b22d430>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1478, in __del__\n",
      "    self._shutdown_workers()\n",
      "  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1461, in _shutdown_workers\n",
      "    if w.is_alive():\n",
      "  File \"/home/user/miniconda3/lib/python3.8/multiprocessing/process.py\", line 160, in is_alive\n",
      "    assert self._parent_pid == os.getpid(), 'can only test a child process'\n",
      "AssertionError: Exception ignored in: can only test a child process<function _MultiProcessingDataLoaderIter.__del__ at 0x7f394b22d430>\n",
      "\n",
      "Traceback (most recent call last):\n",
      "Exception ignored in:   File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1478, in __del__\n",
      "<function _MultiProcessingDataLoaderIter.__del__ at 0x7f394b22d430>    \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1478, in __del__\n",
      "self._shutdown_workers()    \n",
      "self._shutdown_workers()  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1461, in _shutdown_workers\n",
      "\n",
      "  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1461, in _shutdown_workers\n",
      "        Exception ignored in: Exception ignored in: if w.is_alive():<function _MultiProcessingDataLoaderIter.__del__ at 0x7f394b22d430>\n",
      "\n",
      "  File \"/home/user/miniconda3/lib/python3.8/multiprocessing/process.py\", line 160, in is_alive\n",
      "<function _MultiProcessingDataLoaderIter.__del__ at 0x7f394b22d430>Traceback (most recent call last):\n",
      "\n",
      "    if w.is_alive():assert self._parent_pid == os.getpid(), 'can only test a child process'\n",
      "AssertionErrorTraceback (most recent call last):\n",
      ": can only test a child process  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1478, in __del__\n",
      "\n",
      "  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1478, in __del__\n",
      "    \n",
      "      File \"/home/user/miniconda3/lib/python3.8/multiprocessing/process.py\", line 160, in is_alive\n",
      "self._shutdown_workers()    \n",
      "self._shutdown_workers()assert self._parent_pid == os.getpid(), 'can only test a child process'  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1461, in _shutdown_workers\n",
      "\n",
      "\n",
      "Exception ignored in:       File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1461, in _shutdown_workers\n",
      "AssertionErrorif w.is_alive():    : \n",
      "if w.is_alive():can only test a child process<function _MultiProcessingDataLoaderIter.__del__ at 0x7f394b22d430>  File \"/home/user/miniconda3/lib/python3.8/multiprocessing/process.py\", line 160, in is_alive\n",
      "\n",
      "\n",
      "    assert self._parent_pid == os.getpid(), 'can only test a child process'\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1478, in __del__\n",
      "\n",
      "  File \"/home/user/miniconda3/lib/python3.8/multiprocessing/process.py\", line 160, in is_alive\n",
      "    AssertionError    : self._shutdown_workers()can only test a child processassert self._parent_pid == os.getpid(), 'can only test a child process'\n",
      "Exception ignored in: \n",
      "  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1461, in _shutdown_workers\n",
      "\n",
      "AssertionError    : can only test a child processif w.is_alive():<function _MultiProcessingDataLoaderIter.__del__ at 0x7f394b22d430>\n",
      "\n",
      "\n",
      "  File \"/home/user/miniconda3/lib/python3.8/multiprocessing/process.py\", line 160, in is_alive\n",
      "    Traceback (most recent call last):\n",
      "  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1478, in __del__\n",
      "assert self._parent_pid == os.getpid(), 'can only test a child process'Exception ignored in: \n",
      "<function _MultiProcessingDataLoaderIter.__del__ at 0x7f394b22d430>    AssertionError\n",
      "self._shutdown_workers(): Traceback (most recent call last):\n",
      "\n",
      "can only test a child process  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1478, in __del__\n",
      "\n",
      "  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1461, in _shutdown_workers\n",
      "        self._shutdown_workers()if w.is_alive():\n",
      "\n",
      "  File \"/home/user/miniconda3/lib/python3.8/multiprocessing/process.py\", line 160, in is_alive\n",
      "  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1461, in _shutdown_workers\n",
      "        assert self._parent_pid == os.getpid(), 'can only test a child process'if w.is_alive():\n",
      "\n",
      "  File \"/home/user/miniconda3/lib/python3.8/multiprocessing/process.py\", line 160, in is_alive\n",
      "AssertionError    assert self._parent_pid == os.getpid(), 'can only test a child process': can only test a child process\n",
      "\n",
      "AssertionError: can only test a child process\n",
      "1000it [06:06,  2.73it/s]\n",
      "0it [00:00, ?it/s]Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f394b22d430>\n",
      "Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f394b22d430>Traceback (most recent call last):\n",
      "  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1478, in __del__\n",
      "\n",
      "Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f394b22d430>Traceback (most recent call last):\n",
      "  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1478, in __del__\n",
      "\n",
      "        self._shutdown_workers()\n",
      "self._shutdown_workers()Traceback (most recent call last):\n",
      "\n",
      "  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1461, in _shutdown_workers\n",
      "  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1478, in __del__\n",
      "        if w.is_alive():\n",
      "  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1461, in _shutdown_workers\n",
      "  File \"/home/user/miniconda3/lib/python3.8/multiprocessing/process.py\", line 160, in is_alive\n",
      "self._shutdown_workers()\n",
      "        if w.is_alive():  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1461, in _shutdown_workers\n",
      "assert self._parent_pid == os.getpid(), 'can only test a child process'    \n",
      "if w.is_alive():  File \"/home/user/miniconda3/lib/python3.8/multiprocessing/process.py\", line 160, in is_alive\n",
      "Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f394b22d430>\n",
      "    \n",
      "  File \"/home/user/miniconda3/lib/python3.8/multiprocessing/process.py\", line 160, in is_alive\n",
      "    assert self._parent_pid == os.getpid(), 'can only test a child process'assert self._parent_pid == os.getpid(), 'can only test a child process'AssertionError\n",
      "\n",
      "\n",
      "AssertionError: Traceback (most recent call last):\n",
      "can only test a child process: AssertionErrorcan only test a child process  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1478, in __del__\n",
      "\n",
      "\n",
      ": can only test a child process\n",
      "    self._shutdown_workers()Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f394b22d430>\n",
      "\n",
      "  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1461, in _shutdown_workers\n",
      "Traceback (most recent call last):\n",
      "      File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1478, in __del__\n",
      "Exception ignored in:     <function _MultiProcessingDataLoaderIter.__del__ at 0x7f394b22d430>if w.is_alive():\n",
      "self._shutdown_workers()Exception ignored in: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/user/miniconda3/lib/python3.8/multiprocessing/process.py\", line 160, in is_alive\n",
      "  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1478, in __del__\n",
      "\n",
      "<function _MultiProcessingDataLoaderIter.__del__ at 0x7f394b22d430>\n",
      "    Traceback (most recent call last):\n",
      "  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1461, in _shutdown_workers\n",
      "    assert self._parent_pid == os.getpid(), 'can only test a child process'\n",
      "AssertionErrorself._shutdown_workers()  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1478, in __del__\n",
      "        if w.is_alive():\n",
      ": self._shutdown_workers()\n",
      "can only test a child process  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1461, in _shutdown_workers\n",
      "  File \"/home/user/miniconda3/lib/python3.8/multiprocessing/process.py\", line 160, in is_alive\n",
      "\n",
      "        assert self._parent_pid == os.getpid(), 'can only test a child process'\n",
      "  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1461, in _shutdown_workers\n",
      "\n",
      "AssertionError    if w.is_alive():: \n",
      "can only test a child processif w.is_alive():  File \"/home/user/miniconda3/lib/python3.8/multiprocessing/process.py\", line 160, in is_alive\n",
      "\n",
      "Exception ignored in:     \n",
      "<function _MultiProcessingDataLoaderIter.__del__ at 0x7f394b22d430>  File \"/home/user/miniconda3/lib/python3.8/multiprocessing/process.py\", line 160, in is_alive\n",
      "assert self._parent_pid == os.getpid(), 'can only test a child process'    \n",
      "assert self._parent_pid == os.getpid(), 'can only test a child process'Traceback (most recent call last):\n",
      "\n",
      "\n",
      "  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1478, in __del__\n",
      "AssertionErrorAssertionError    : self._shutdown_workers(): can only test a child processcan only test a child process\n",
      "  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1461, in _shutdown_workers\n",
      "\n",
      "\n",
      "    if w.is_alive():\n",
      "  File \"/home/user/miniconda3/lib/python3.8/multiprocessing/process.py\", line 160, in is_alive\n",
      "    assert self._parent_pid == os.getpid(), 'can only test a child process'\n",
      "AssertionError: can only test a child process\n",
      "99it [00:24,  4.11it/s]\n",
      "0it [00:00, ?it/s]Exception ignored in: Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f394b22d430><function _MultiProcessingDataLoaderIter.__del__ at 0x7f394b22d430>\n",
      "Traceback (most recent call last):\n",
      "Exception ignored in:   File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1478, in __del__\n",
      "<function _MultiProcessingDataLoaderIter.__del__ at 0x7f394b22d430>\n",
      "    self._shutdown_workers()\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1461, in _shutdown_workers\n",
      "  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1478, in __del__\n",
      "    \n",
      "if w.is_alive():    Traceback (most recent call last):\n",
      "\n",
      "  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1478, in __del__\n",
      "self._shutdown_workers()  File \"/home/user/miniconda3/lib/python3.8/multiprocessing/process.py\", line 160, in is_alive\n",
      "\n",
      "          File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1461, in _shutdown_workers\n",
      "assert self._parent_pid == os.getpid(), 'can only test a child process'self._shutdown_workers()Exception ignored in: \n",
      "    \n",
      "AssertionErrorif w.is_alive():<function _MultiProcessingDataLoaderIter.__del__ at 0x7f394b22d430>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1461, in _shutdown_workers\n",
      "  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1478, in __del__\n",
      "    \n",
      "  File \"/home/user/miniconda3/lib/python3.8/multiprocessing/process.py\", line 160, in is_alive\n",
      "    : Exception ignored in: if w.is_alive():can only test a child process\n",
      "<function _MultiProcessingDataLoaderIter.__del__ at 0x7f394b22d430>self._shutdown_workers()  File \"/home/user/miniconda3/lib/python3.8/multiprocessing/process.py\", line 160, in is_alive\n",
      "\n",
      "    \n",
      "  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1461, in _shutdown_workers\n",
      "Exception ignored in: Traceback (most recent call last):\n",
      "    assert self._parent_pid == os.getpid(), 'can only test a child process'  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1478, in __del__\n",
      "\n",
      "\n",
      "    AssertionError:     can only test a child processif w.is_alive():\n",
      "self._shutdown_workers()\n",
      "  File \"/home/user/miniconda3/lib/python3.8/multiprocessing/process.py\", line 160, in is_alive\n",
      "<function _MultiProcessingDataLoaderIter.__del__ at 0x7f394b22d430>assert self._parent_pid == os.getpid(), 'can only test a child process'    \n",
      "assert self._parent_pid == os.getpid(), 'can only test a child process'\n",
      "\n",
      "\n",
      "AssertionError  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1461, in _shutdown_workers\n",
      "Traceback (most recent call last):\n",
      ":   File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1478, in __del__\n",
      "    can only test a child processif w.is_alive():\n",
      "\n",
      "  File \"/home/user/miniconda3/lib/python3.8/multiprocessing/process.py\", line 160, in is_alive\n",
      "AssertionErrorException ignored in:         <function _MultiProcessingDataLoaderIter.__del__ at 0x7f394b22d430>assert self._parent_pid == os.getpid(), 'can only test a child process': self._shutdown_workers()can only test a child process\n",
      "Exception ignored in: \n",
      "\n",
      "Traceback (most recent call last):\n",
      "\n",
      "<function _MultiProcessingDataLoaderIter.__del__ at 0x7f394b22d430>  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1478, in __del__\n",
      "  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1461, in _shutdown_workers\n",
      "AssertionError    Exception ignored in:     : <function _MultiProcessingDataLoaderIter.__del__ at 0x7f394b22d430>if w.is_alive():\n",
      "can only test a child processself._shutdown_workers()Traceback (most recent call last):\n",
      "\n",
      "Exception ignored in: \n",
      "<function _MultiProcessingDataLoaderIter.__del__ at 0x7f394b22d430>\n",
      "Exception ignored in:   File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1478, in __del__\n",
      "\n",
      "\n",
      "  File \"/home/user/miniconda3/lib/python3.8/multiprocessing/process.py\", line 160, in is_alive\n",
      "Traceback (most recent call last):\n",
      "    Traceback (most recent call last):\n",
      "  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1461, in _shutdown_workers\n",
      "self._shutdown_workers()    <function _MultiProcessingDataLoaderIter.__del__ at 0x7f394b22d430>\n",
      "  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1478, in __del__\n",
      "  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1478, in __del__\n",
      "  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1461, in _shutdown_workers\n",
      "    assert self._parent_pid == os.getpid(), 'can only test a child process'    \n",
      "if w.is_alive():\n",
      "AssertionError    :     Exception ignored in: self._shutdown_workers()Traceback (most recent call last):\n",
      "can only test a child processself._shutdown_workers()if w.is_alive():\n",
      "Exception ignored in: \n",
      "  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1478, in __del__\n",
      "<function _MultiProcessingDataLoaderIter.__del__ at 0x7f394b22d430>\n",
      "\n",
      "  File \"/home/user/miniconda3/lib/python3.8/multiprocessing/process.py\", line 160, in is_alive\n",
      "<function _MultiProcessingDataLoaderIter.__del__ at 0x7f394b22d430>    \n",
      "  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1461, in _shutdown_workers\n",
      "\n",
      "  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1461, in _shutdown_workers\n",
      "\n",
      "self._shutdown_workers()    Traceback (most recent call last):\n",
      "      File \"/home/user/miniconda3/lib/python3.8/multiprocessing/process.py\", line 160, in is_alive\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1478, in __del__\n",
      "    \n",
      "  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1478, in __del__\n",
      "    if w.is_alive():assert self._parent_pid == os.getpid(), 'can only test a child process'if w.is_alive():  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1461, in _shutdown_workers\n",
      "    \n",
      "    AssertionError    \n",
      "\n",
      "if w.is_alive():self._shutdown_workers()assert self._parent_pid == os.getpid(), 'can only test a child process'self._shutdown_workers()  File \"/home/user/miniconda3/lib/python3.8/multiprocessing/process.py\", line 160, in is_alive\n",
      "Exception ignored in:   File \"/home/user/miniconda3/lib/python3.8/multiprocessing/process.py\", line 160, in is_alive\n",
      "\n",
      "    : <function _MultiProcessingDataLoaderIter.__del__ at 0x7f394b22d430>\n",
      "  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1461, in _shutdown_workers\n",
      "\n",
      "\n",
      "    AssertionErrorcan only test a child process  File \"/home/user/miniconda3/lib/python3.8/multiprocessing/process.py\", line 160, in is_alive\n",
      "assert self._parent_pid == os.getpid(), 'can only test a child process'  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1461, in _shutdown_workers\n",
      "    \n",
      ":     assert self._parent_pid == os.getpid(), 'can only test a child process'    can only test a child processassert self._parent_pid == os.getpid(), 'can only test a child process'if w.is_alive():\n",
      "\n",
      "\n",
      "\n",
      "AssertionErrorif w.is_alive():\n",
      "AssertionError:   File \"/home/user/miniconda3/lib/python3.8/multiprocessing/process.py\", line 160, in is_alive\n",
      "AssertionErrorTraceback (most recent call last):\n",
      "    : :   File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1478, in __del__\n",
      "\n",
      "assert self._parent_pid == os.getpid(), 'can only test a child process'can only test a child process\n",
      "can only test a child processcan only test a child process      File \"/home/user/miniconda3/lib/python3.8/multiprocessing/process.py\", line 160, in is_alive\n",
      "\n",
      "\n",
      "self._shutdown_workers()AssertionError\n",
      "\n",
      ": \n",
      "      File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1461, in _shutdown_workers\n",
      "    can only test a child processif w.is_alive():\n",
      "\n",
      "  File \"/home/user/miniconda3/lib/python3.8/multiprocessing/process.py\", line 160, in is_alive\n",
      "    assert self._parent_pid == os.getpid(), 'can only test a child process'\n",
      "AssertionErrorException ignored in: : <function _MultiProcessingDataLoaderIter.__del__ at 0x7f394b22d430>can only test a child process\n",
      "Exception ignored in: \n",
      "Traceback (most recent call last):\n",
      "<function _MultiProcessingDataLoaderIter.__del__ at 0x7f394b22d430>assert self._parent_pid == os.getpid(), 'can only test a child process'\n",
      "  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1478, in __del__\n",
      "\n",
      "Traceback (most recent call last):\n",
      "    AssertionErrorself._shutdown_workers():   File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1478, in __del__\n",
      "can only test a child process\n",
      "      File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1461, in _shutdown_workers\n",
      "self._shutdown_workers()\n",
      "    \n",
      "if w.is_alive():  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1461, in _shutdown_workers\n",
      "    if w.is_alive():\n",
      "\n",
      "  File \"/home/user/miniconda3/lib/python3.8/multiprocessing/process.py\", line 160, in is_alive\n",
      "  File \"/home/user/miniconda3/lib/python3.8/multiprocessing/process.py\", line 160, in is_alive\n",
      "    assert self._parent_pid == os.getpid(), 'can only test a child process'    assert self._parent_pid == os.getpid(), 'can only test a child process'\n",
      "\n",
      "AssertionErrorAssertionError: : can only test a child processcan only test a child process\n",
      "\n",
      "1000it [06:02,  2.76it/s]\n",
      "Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f394b22d430>Exception ignored in: Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f394b22d430><function _MultiProcessingDataLoaderIter.__del__ at 0x7f394b22d430>\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1478, in __del__\n",
      "Traceback (most recent call last):\n",
      "\n",
      "    Traceback (most recent call last):\n",
      "Exception ignored in: self._shutdown_workers()  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1478, in __del__\n",
      "  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1478, in __del__\n",
      "\n",
      "<function _MultiProcessingDataLoaderIter.__del__ at 0x7f394b22d430>        \n",
      "self._shutdown_workers()  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1461, in _shutdown_workers\n",
      "Traceback (most recent call last):\n",
      "self._shutdown_workers()  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1478, in __del__\n",
      "  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1461, in _shutdown_workers\n",
      "\n",
      "\n",
      "      File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1461, in _shutdown_workers\n",
      "            self._shutdown_workers()if w.is_alive():\n",
      "if w.is_alive():  File \"/home/user/miniconda3/lib/python3.8/multiprocessing/process.py\", line 160, in is_alive\n",
      "\n",
      "      File \"/home/user/miniconda3/lib/python3.8/multiprocessing/process.py\", line 160, in is_alive\n",
      "assert self._parent_pid == os.getpid(), 'can only test a child process'    if w.is_alive():\n",
      "\n",
      "    AssertionError\n",
      "assert self._parent_pid == os.getpid(), 'can only test a child process'  File \"/home/user/miniconda3/lib/python3.8/multiprocessing/process.py\", line 160, in is_alive\n",
      ": can only test a child process\n",
      "\n",
      "  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1461, in _shutdown_workers\n",
      "    AssertionErrorif w.is_alive():assert self._parent_pid == os.getpid(), 'can only test a child process': \n",
      "can only test a child process\n",
      "0it [00:00, ?it/s]AssertionError  File \"/home/user/miniconda3/lib/python3.8/multiprocessing/process.py\", line 160, in is_alive\n",
      "\n",
      "    : can only test a child processassert self._parent_pid == os.getpid(), 'can only test a child process'\n",
      "\n",
      "AssertionError: can only test a child process\n",
      "Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f394b22d430>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1478, in __del__\n",
      "Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f394b22d430>    \n",
      "self._shutdown_workers()Traceback (most recent call last):\n",
      "  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1478, in __del__\n",
      "\n",
      "  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1461, in _shutdown_workers\n",
      "        self._shutdown_workers()\n",
      "  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1461, in _shutdown_workers\n",
      "    if w.is_alive():Exception ignored in: if w.is_alive():\n",
      "<function _MultiProcessingDataLoaderIter.__del__ at 0x7f394b22d430>\n",
      "  File \"/home/user/miniconda3/lib/python3.8/multiprocessing/process.py\", line 160, in is_alive\n",
      "  File \"/home/user/miniconda3/lib/python3.8/multiprocessing/process.py\", line 160, in is_alive\n",
      "\n",
      "        assert self._parent_pid == os.getpid(), 'can only test a child process'assert self._parent_pid == os.getpid(), 'can only test a child process'\n",
      "AssertionErrorTraceback (most recent call last):\n",
      "\n",
      "  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1478, in __del__\n",
      "AssertionError:     : can only test a child processcan only test a child process\n",
      "self._shutdown_workers()\n",
      "  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1461, in _shutdown_workers\n",
      "\n",
      "Exception ignored in:     <function _MultiProcessingDataLoaderIter.__del__ at 0x7f394b22d430>\n",
      "if w.is_alive():Traceback (most recent call last):\n",
      "  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1478, in __del__\n",
      "\n",
      "      File \"/home/user/miniconda3/lib/python3.8/multiprocessing/process.py\", line 160, in is_alive\n",
      "Exception ignored in:     self._shutdown_workers()assert self._parent_pid == os.getpid(), 'can only test a child process'<function _MultiProcessingDataLoaderIter.__del__ at 0x7f394b22d430>Exception ignored in: \n",
      "\n",
      "\n",
      "Traceback (most recent call last):\n",
      "AssertionError  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1461, in _shutdown_workers\n",
      ":   File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1478, in __del__\n",
      "<function _MultiProcessingDataLoaderIter.__del__ at 0x7f394b22d430>    can only test a child processif w.is_alive():    \n",
      "self._shutdown_workers()\n",
      "\n",
      "\n",
      "  File \"/home/user/miniconda3/lib/python3.8/multiprocessing/process.py\", line 160, in is_alive\n",
      "Traceback (most recent call last):\n",
      "      File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1478, in __del__\n",
      "assert self._parent_pid == os.getpid(), 'can only test a child process'\n",
      "  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1461, in _shutdown_workers\n",
      "AssertionError        if w.is_alive():\n",
      "self._shutdown_workers()  File \"/home/user/miniconda3/lib/python3.8/multiprocessing/process.py\", line 160, in is_alive\n",
      ":     \n",
      "can only test a child processassert self._parent_pid == os.getpid(), 'can only test a child process'Exception ignored in: \n",
      "<function _MultiProcessingDataLoaderIter.__del__ at 0x7f394b22d430>  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1461, in _shutdown_workers\n",
      "\n",
      "AssertionError\n",
      "1it [00:01,  1.59s/it]    : Traceback (most recent call last):\n",
      "can only test a child processif w.is_alive():  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1478, in __del__\n",
      "\n",
      "\n",
      "Exception ignored in:   File \"/home/user/miniconda3/lib/python3.8/multiprocessing/process.py\", line 160, in is_alive\n",
      "    <function _MultiProcessingDataLoaderIter.__del__ at 0x7f394b22d430>\n",
      "Traceback (most recent call last):\n",
      "assert self._parent_pid == os.getpid(), 'can only test a child process'  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1478, in __del__\n",
      "\n",
      "AssertionError    :     can only test a child processself._shutdown_workers()self._shutdown_workers()\n",
      "\n",
      "  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1461, in _shutdown_workers\n",
      "\n",
      "  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1461, in _shutdown_workers\n",
      "        if w.is_alive():if w.is_alive():\n",
      "  File \"/home/user/miniconda3/lib/python3.8/multiprocessing/process.py\", line 160, in is_alive\n",
      "    \n",
      "assert self._parent_pid == os.getpid(), 'can only test a child process'\n",
      "  File \"/home/user/miniconda3/lib/python3.8/multiprocessing/process.py\", line 160, in is_alive\n",
      "AssertionError:     can only test a child process\n",
      "assert self._parent_pid == os.getpid(), 'can only test a child process'\n",
      "AssertionError: can only test a child process\n",
      "99it [00:25,  3.95it/s]\n",
      "Exception ignored in: Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f394b22d430>Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f394b22d430>\n",
      "<function _MultiProcessingDataLoaderIter.__del__ at 0x7f394b22d430>\n",
      "0it [00:00, ?it/s]Traceback (most recent call last):\n",
      "\n",
      "  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1478, in __del__\n",
      "Traceback (most recent call last):\n",
      "Traceback (most recent call last):\n",
      "Exception ignored in:     Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f394b22d430>  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1478, in __del__\n",
      "self._shutdown_workers()\n",
      "<function _MultiProcessingDataLoaderIter.__del__ at 0x7f394b22d430>Traceback (most recent call last):\n",
      "\n",
      "  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1478, in __del__\n",
      "      File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1461, in _shutdown_workers\n",
      "  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1478, in __del__\n",
      "Exception ignored in: \n",
      "        self._shutdown_workers()self._shutdown_workers()    if w.is_alive():Exception ignored in: Traceback (most recent call last):\n",
      "<function _MultiProcessingDataLoaderIter.__del__ at 0x7f394b22d430>\n",
      "self._shutdown_workers()  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1461, in _shutdown_workers\n",
      "<function _MultiProcessingDataLoaderIter.__del__ at 0x7f394b22d430>\n",
      "\n",
      "\n",
      "  File \"/home/user/miniconda3/lib/python3.8/multiprocessing/process.py\", line 160, in is_alive\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1478, in __del__\n",
      "          File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1461, in _shutdown_workers\n",
      "\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1461, in _shutdown_workers\n",
      "        self._shutdown_workers()  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1478, in __del__\n",
      "if w.is_alive():assert self._parent_pid == os.getpid(), 'can only test a child process'    if w.is_alive():\n",
      "self._shutdown_workers()\n",
      "    \n",
      "\n",
      "  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1461, in _shutdown_workers\n",
      "  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1478, in __del__\n",
      "\n",
      "  File \"/home/user/miniconda3/lib/python3.8/multiprocessing/process.py\", line 160, in is_alive\n",
      "    if w.is_alive():      File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1461, in _shutdown_workers\n",
      "if w.is_alive():\n",
      "AssertionError  File \"/home/user/miniconda3/lib/python3.8/multiprocessing/process.py\", line 160, in is_alive\n",
      ":   File \"/home/user/miniconda3/lib/python3.8/multiprocessing/process.py\", line 160, in is_alive\n",
      "        assert self._parent_pid == os.getpid(), 'can only test a child process'    self._shutdown_workers()if w.is_alive():    \n",
      "assert self._parent_pid == os.getpid(), 'can only test a child process'can only test a child process\n",
      "\n",
      "assert self._parent_pid == os.getpid(), 'can only test a child process'\n",
      "  File \"/home/user/miniconda3/lib/python3.8/multiprocessing/process.py\", line 160, in is_alive\n",
      "\n",
      "\n",
      "  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1461, in _shutdown_workers\n",
      "\n",
      "AssertionError  File \"/home/user/miniconda3/lib/python3.8/multiprocessing/process.py\", line 160, in is_alive\n",
      "AssertionError    :     if w.is_alive():can only test a child processException ignored in: assert self._parent_pid == os.getpid(), 'can only test a child process':     can only test a child process\n",
      "<function _MultiProcessingDataLoaderIter.__del__ at 0x7f394b22d430>assert self._parent_pid == os.getpid(), 'can only test a child process'\n",
      "  File \"/home/user/miniconda3/lib/python3.8/multiprocessing/process.py\", line 160, in is_alive\n",
      "\n",
      "\n",
      "\n",
      "\n",
      "    Traceback (most recent call last):\n",
      "AssertionErrorassert self._parent_pid == os.getpid(), 'can only test a child process'AssertionError  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1478, in __del__\n",
      "\n",
      "AssertionError: AssertionError: : Exception ignored in: can only test a child process:     \n",
      "<function _MultiProcessingDataLoaderIter.__del__ at 0x7f394b22d430>Exception ignored in: \n",
      "can only test a child processself._shutdown_workers()Traceback (most recent call last):\n",
      "<function _MultiProcessingDataLoaderIter.__del__ at 0x7f394b22d430>\n",
      "  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1478, in __del__\n",
      "\n",
      "    \n",
      "self._shutdown_workers()can only test a child process  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1461, in _shutdown_workers\n",
      "\n",
      "\n",
      "Exception ignored in: Traceback (most recent call last):\n",
      "can only test a child process  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1461, in _shutdown_workers\n",
      "<function _MultiProcessingDataLoaderIter.__del__ at 0x7f394b22d430>        \n",
      "if w.is_alive():  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1478, in __del__\n",
      "\n",
      "    \n",
      "self._shutdown_workers()  File \"/home/user/miniconda3/lib/python3.8/multiprocessing/process.py\", line 160, in is_alive\n",
      "\n",
      "if w.is_alive():      File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1461, in _shutdown_workers\n",
      "assert self._parent_pid == os.getpid(), 'can only test a child process'    \n",
      "Traceback (most recent call last):\n",
      "\n",
      "if w.is_alive():  File \"/home/user/miniconda3/lib/python3.8/multiprocessing/process.py\", line 160, in is_alive\n",
      "  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1478, in __del__\n",
      "AssertionErrorException ignored in: Exception ignored in:     \n",
      "Exception ignored in:     self._shutdown_workers()Exception ignored in:   File \"/home/user/miniconda3/lib/python3.8/multiprocessing/process.py\", line 160, in is_alive\n",
      "<function _MultiProcessingDataLoaderIter.__del__ at 0x7f394b22d430><function _MultiProcessingDataLoaderIter.__del__ at 0x7f394b22d430>\n",
      "\n",
      "    Traceback (most recent call last):\n",
      "<function _MultiProcessingDataLoaderIter.__del__ at 0x7f394b22d430>  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1478, in __del__\n",
      "assert self._parent_pid == os.getpid(), 'can only test a child process': \n",
      "  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1461, in _shutdown_workers\n",
      "Traceback (most recent call last):\n",
      "\n",
      "    <function _MultiProcessingDataLoaderIter.__del__ at 0x7f394b22d430>self._shutdown_workers()assert self._parent_pid == os.getpid(), 'can only test a child process'  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1478, in __del__\n",
      "    \n",
      "AssertionErrorcan only test a child process\n",
      "\n",
      "\n",
      "if w.is_alive():\n",
      "AssertionError  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1461, in _shutdown_workers\n",
      ": Traceback (most recent call last):\n",
      "    : can only test a child process  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1478, in __del__\n",
      "self._shutdown_workers()    can only test a child process    \n",
      "self._shutdown_workers()\n",
      "Traceback (most recent call last):\n",
      "\n",
      "\n",
      "  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1478, in __del__\n",
      "  File \"/home/user/miniconda3/lib/python3.8/multiprocessing/process.py\", line 160, in is_alive\n",
      "\n",
      "  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1461, in _shutdown_workers\n",
      "  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1461, in _shutdown_workers\n",
      "                if w.is_alive():self._shutdown_workers()if w.is_alive():if w.is_alive():\n",
      "\n",
      "\n",
      "  File \"/home/user/miniconda3/lib/python3.8/multiprocessing/process.py\", line 160, in is_alive\n",
      "  File \"/home/user/miniconda3/lib/python3.8/multiprocessing/process.py\", line 160, in is_alive\n",
      "\n",
      "    assert self._parent_pid == os.getpid(), 'can only test a child process'      File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1461, in _shutdown_workers\n",
      "\n",
      "      File \"/home/user/miniconda3/lib/python3.8/multiprocessing/process.py\", line 160, in is_alive\n",
      "assert self._parent_pid == os.getpid(), 'can only test a child process'if w.is_alive():AssertionError\n",
      ": \n",
      "  File \"/home/user/miniconda3/lib/python3.8/multiprocessing/process.py\", line 160, in is_alive\n",
      "can only test a child processAssertionErrorassert self._parent_pid == os.getpid(), 'can only test a child process'\n",
      "Exception ignored in: \n",
      ": <function _MultiProcessingDataLoaderIter.__del__ at 0x7f394b22d430>AssertionErrorcan only test a child process\n",
      "\n",
      "        : assert self._parent_pid == os.getpid(), 'can only test a child process'can only test a child processassert self._parent_pid == os.getpid(), 'can only test a child process'\n",
      "Traceback (most recent call last):\n",
      "\n",
      "AssertionError  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1478, in __del__\n",
      "\n",
      ": can only test a child processAssertionError\n",
      ":     can only test a child processself._shutdown_workers()\n",
      "  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1461, in _shutdown_workers\n",
      "    if w.is_alive():\n",
      "\n",
      "  File \"/home/user/miniconda3/lib/python3.8/multiprocessing/process.py\", line 160, in is_alive\n",
      "    assert self._parent_pid == os.getpid(), 'can only test a child process'\n",
      "AssertionError: can only test a child process\n",
      "1000it [06:07,  2.72it/s]\n",
      "0it [00:00, ?it/s]in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f394b22d430>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1478, in __del__\n",
      "    self._shutdown_workers()Exception ignored in: \n",
      "<function _MultiProcessingDataLoaderIter.__del__ at 0x7f394b22d430>  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1461, in _shutdown_workers\n",
      "\n",
      "Exception ignored in:     Traceback (most recent call last):\n",
      "<function _MultiProcessingDataLoaderIter.__del__ at 0x7f394b22d430>if w.is_alive():  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1478, in __del__\n",
      "\n",
      "\n",
      "      File \"/home/user/miniconda3/lib/python3.8/multiprocessing/process.py\", line 160, in is_alive\n",
      "Traceback (most recent call last):\n",
      "self._shutdown_workers()    \n",
      "assert self._parent_pid == os.getpid(), 'can only test a child process'  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1478, in __del__\n",
      "  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1461, in _shutdown_workers\n",
      "\n",
      "AssertionError        self._shutdown_workers(): if w.is_alive():\n",
      "can only test a child process  File \"/home/user/miniconda3/lib/python3.8/multiprocessing/process.py\", line 160, in is_alive\n",
      "\n",
      "\n",
      "      File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1461, in _shutdown_workers\n",
      "assert self._parent_pid == os.getpid(), 'can only test a child process'\n",
      "    AssertionErrorif w.is_alive():: \n",
      "  File \"/home/user/miniconda3/lib/python3.8/multiprocessing/process.py\", line 160, in is_alive\n",
      "    assert self._parent_pid == os.getpid(), 'can only test a child process'\n",
      "AssertionError: Exception ignored in: can only test a child process\n",
      "can only test a child process\n",
      "<function _MultiProcessingDataLoaderIter.__del__ at 0x7f394b22d430>\n",
      "Traceback (most recent call last):\n",
      "Exception ignored in:   File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1478, in __del__\n",
      "<function _MultiProcessingDataLoaderIter.__del__ at 0x7f394b22d430>    Exception ignored in: self._shutdown_workers()\n",
      "<function _MultiProcessingDataLoaderIter.__del__ at 0x7f394b22d430>\n",
      "Traceback (most recent call last):\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1478, in __del__\n",
      "      File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1461, in _shutdown_workers\n",
      "  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1478, in __del__\n",
      "self._shutdown_workers()    \n",
      "if w.is_alive():      File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1461, in _shutdown_workers\n",
      "\n",
      "self._shutdown_workers()    if w.is_alive():\n",
      "  File \"/home/user/miniconda3/lib/python3.8/multiprocessing/process.py\", line 160, in is_alive\n",
      "\n",
      "  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1461, in _shutdown_workers\n",
      "      File \"/home/user/miniconda3/lib/python3.8/multiprocessing/process.py\", line 160, in is_alive\n",
      "assert self._parent_pid == os.getpid(), 'can only test a child process'        \n",
      "if w.is_alive():assert self._parent_pid == os.getpid(), 'can only test a child process'AssertionError\n",
      "\n",
      ":   File \"/home/user/miniconda3/lib/python3.8/multiprocessing/process.py\", line 160, in is_alive\n",
      "AssertionErrorcan only test a child process\n",
      ": can only test a child process\n",
      "    assert self._parent_pid == os.getpid(), 'can only test a child process'Exception ignored in: \n",
      "Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f394b22d430>AssertionError\n",
      "<function _MultiProcessingDataLoaderIter.__del__ at 0x7f394b22d430>: Traceback (most recent call last):\n",
      "\n",
      "can only test a child processTraceback (most recent call last):\n",
      "\n",
      "  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1478, in __del__\n",
      "    self._shutdown_workers()  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1478, in __del__\n",
      "    \n",
      "  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1461, in _shutdown_workers\n",
      "self._shutdown_workers()    if w.is_alive():\n",
      "Exception ignored in: \n",
      "  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1461, in _shutdown_workers\n",
      "  File \"/home/user/miniconda3/lib/python3.8/multiprocessing/process.py\", line 160, in is_alive\n",
      "<function _MultiProcessingDataLoaderIter.__del__ at 0x7f394b22d430>        \n",
      "if w.is_alive():Traceback (most recent call last):\n",
      "  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1478, in __del__\n",
      "    assert self._parent_pid == os.getpid(), 'can only test a child process'\n",
      "\n",
      "self._shutdown_workers()AssertionError\n",
      "  File \"/home/user/miniconda3/lib/python3.8/multiprocessing/process.py\", line 160, in is_alive\n",
      "  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1461, in _shutdown_workers\n",
      "    : assert self._parent_pid == os.getpid(), 'can only test a child process'    \n",
      "can only test a child processAssertionError\n",
      ": can only test a child processif w.is_alive():\n",
      "\n",
      "  File \"/home/user/miniconda3/lib/python3.8/multiprocessing/process.py\", line 160, in is_alive\n",
      "    assert self._parent_pid == os.getpid(), 'can only test a child process'\n",
      "AssertionError: can only test a child process\n",
      "99it [00:23,  4.23it/s]\n",
      "1000it [06:14,  2.67it/s]\n",
      "Exception ignored in: if w.is_alive():<function _MultiProcessingDataLoaderIter.__del__ at 0x7f394b22d430>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1478, in __del__\n",
      "0it [00:00, ?it/s]self._shutdown_workers()\n",
      "  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1461, in _shutdown_workers\n",
      "Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f394b22d430>    if w.is_alive():\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/user/miniconda3/lib/python3.8/multiprocessing/process.py\", line 160, in is_alive\n",
      "  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1478, in __del__\n",
      "        assert self._parent_pid == os.getpid(), 'can only test a child process'self._shutdown_workers()\n",
      "\n",
      "AssertionError: can only test a child process  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1461, in _shutdown_workers\n",
      "\n",
      "    \n",
      "  File \"/home/user/miniconda3/lib/python3.8/multiprocessing/process.py\", line 160, in is_alive\n",
      "    assert self._parent_pid == os.getpid(), 'can only test a child process'\n",
      "AssertionError: can only test a child process\n",
      "99it [00:23,  4.20it/s]\n",
      "1000it [06:36,  2.52it/s]\n",
      "0it [00:00, ?it/s]Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f394b22d430>\n",
      "Traceback (most recent call last):\n",
      "Exception ignored in:   File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1478, in __del__\n",
      "Exception ignored in:     <function _MultiProcessingDataLoaderIter.__del__ at 0x7f394b22d430><function _MultiProcessingDataLoaderIter.__del__ at 0x7f394b22d430>\n",
      "self._shutdown_workers()Exception ignored in: \n",
      "\n",
      "<function _MultiProcessingDataLoaderIter.__del__ at 0x7f394b22d430>  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1461, in _shutdown_workers\n",
      "Traceback (most recent call last):\n",
      "\n",
      "    Traceback (most recent call last):\n",
      "  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1478, in __del__\n",
      "if w.is_alive():    self._shutdown_workers()  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1478, in __del__\n",
      "Traceback (most recent call last):\n",
      "\n",
      "  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1478, in __del__\n",
      "  File \"/home/user/miniconda3/lib/python3.8/multiprocessing/process.py\", line 160, in is_alive\n",
      "        \n",
      "assert self._parent_pid == os.getpid(), 'can only test a child process'\n",
      "  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1461, in _shutdown_workers\n",
      "    AssertionError: self._shutdown_workers()    self._shutdown_workers()\n",
      "if w.is_alive():  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1461, in _shutdown_workers\n",
      "\n",
      "can only test a child process    \n",
      "  File \"/home/user/miniconda3/lib/python3.8/multiprocessing/process.py\", line 160, in is_alive\n",
      "if w.is_alive():      File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1461, in _shutdown_workers\n",
      "assert self._parent_pid == os.getpid(), 'can only test a child process'\n",
      "\n",
      "    \n",
      "  File \"/home/user/miniconda3/lib/python3.8/multiprocessing/process.py\", line 160, in is_alive\n",
      "AssertionErrorif w.is_alive():    \n",
      "assert self._parent_pid == os.getpid(), 'can only test a child process'  File \"/home/user/miniconda3/lib/python3.8/multiprocessing/process.py\", line 160, in is_alive\n",
      "\n",
      "    : assert self._parent_pid == os.getpid(), 'can only test a child process'can only test a child processAssertionError: \n",
      "\n",
      "AssertionErrorcan only test a child process\n",
      ": can only test a child process\n",
      "99it [00:24,  4.09it/s]\n",
      "0it [00:00, ?it/s]Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f394b22d430>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1478, in __del__\n",
      "    self._shutdown_workers()\n",
      "Exception ignored in:   File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1461, in _shutdown_workers\n",
      "Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f394b22d430>    \n",
      "<function _MultiProcessingDataLoaderIter.__del__ at 0x7f394b22d430>if w.is_alive():\n",
      "Exception ignored in: Exception ignored in: \n",
      "Traceback (most recent call last):\n",
      "<function _MultiProcessingDataLoaderIter.__del__ at 0x7f394b22d430>  File \"/home/user/miniconda3/lib/python3.8/multiprocessing/process.py\", line 160, in is_alive\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1478, in __del__\n",
      "Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f394b22d430>    Exception ignored in: \n",
      "    self._shutdown_workers()\n",
      "  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1478, in __del__\n",
      "Traceback (most recent call last):\n",
      "      File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1478, in __del__\n",
      "assert self._parent_pid == os.getpid(), 'can only test a child process'<function _MultiProcessingDataLoaderIter.__del__ at 0x7f394b22d430>    \n",
      "self._shutdown_workers()Traceback (most recent call last):\n",
      "\n",
      "AssertionError  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1478, in __del__\n",
      "Traceback (most recent call last):\n",
      "\n",
      "\n",
      ":   File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1478, in __del__\n",
      "  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1461, in _shutdown_workers\n",
      "self._shutdown_workers()      File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1461, in _shutdown_workers\n",
      "can only test a child process        \n",
      "if w.is_alive():self._shutdown_workers()  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1461, in _shutdown_workers\n",
      "    <function _MultiProcessingDataLoaderIter.__del__ at 0x7f394b22d430>self._shutdown_workers()    \n",
      "\n",
      "\n",
      "\n",
      "if w.is_alive():  File \"/home/user/miniconda3/lib/python3.8/multiprocessing/process.py\", line 160, in is_alive\n",
      "  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1461, in _shutdown_workers\n",
      "    \n",
      "  File \"/home/user/miniconda3/lib/python3.8/multiprocessing/process.py\", line 160, in is_alive\n",
      "if w.is_alive():    \n",
      "    \n",
      "assert self._parent_pid == os.getpid(), 'can only test a child process'Traceback (most recent call last):\n",
      "assert self._parent_pid == os.getpid(), 'can only test a child process'\n",
      "  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1461, in _shutdown_workers\n",
      "if w.is_alive():\n",
      "AssertionError\n",
      "AssertionError  File \"/home/user/miniconda3/lib/python3.8/multiprocessing/process.py\", line 160, in is_alive\n",
      ":   File \"/home/user/miniconda3/lib/python3.8/multiprocessing/process.py\", line 160, in is_alive\n",
      "can only test a child process: \n",
      "        assert self._parent_pid == os.getpid(), 'can only test a child process'    \n",
      "AssertionErrorif w.is_alive():  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1478, in __del__\n",
      "assert self._parent_pid == os.getpid(), 'can only test a child process': can only test a child process\n",
      "  File \"/home/user/miniconda3/lib/python3.8/multiprocessing/process.py\", line 160, in is_alive\n",
      "    assert self._parent_pid == os.getpid(), 'can only test a child process'\n",
      "AssertionError: can only test a child process\n",
      "    \n",
      "\n",
      "can only test a child processAssertionErrorself._shutdown_workers()\n",
      ": \n",
      "can only test a child process\n",
      "  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1461, in _shutdown_workers\n",
      "    if w.is_alive():Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f394b22d430>\n",
      "\n",
      "  File \"/home/user/miniconda3/lib/python3.8/multiprocessing/process.py\", line 160, in is_alive\n",
      "    assert self._parent_pid == os.getpid(), 'can only test a child process'\n",
      "AssertionError: can only test a child processTraceback (most recent call last):\n",
      "\n",
      "  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1478, in __del__\n",
      "    self._shutdown_workers()\n",
      "  File \"/home/user/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py\", line 1461, in _shutdown_workers\n",
      "    if w.is_alive():\n",
      "  File \"/home/user/miniconda3/lib/python3.8/multiprocessing/process.py\", line 160, in is_alive\n",
      "    assert self._parent_pid == os.getpid(), 'can only test a child process'\n",
      "AssertionError: can only test a child process\n",
      "5it [00:06,  1.35s/it]\n"
     ]
    },
    {
     "ename": "KeyboardInterrupt",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mKeyboardInterrupt\u001b[0m                         Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[35], line 67\u001b[0m\n\u001b[1;32m     65\u001b[0m n_batch \u001b[38;5;241m=\u001b[39m anchors\u001b[38;5;241m.\u001b[39mshape[\u001b[38;5;241m0\u001b[39m]\n\u001b[1;32m     66\u001b[0m anchors \u001b[38;5;241m=\u001b[39m anchors\u001b[38;5;241m.\u001b[39mcuda()\n\u001b[0;32m---> 67\u001b[0m positives \u001b[38;5;241m=\u001b[39m \u001b[43mpositives\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mcuda\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m     68\u001b[0m anchors_lengths \u001b[38;5;241m=\u001b[39m torch\u001b[38;5;241m.\u001b[39mas_tensor([anchor\u001b[38;5;241m.\u001b[39mshape[\u001b[38;5;241m1\u001b[39m] \u001b[38;5;28;01mfor\u001b[39;00m anchor \u001b[38;5;129;01min\u001b[39;00m anchors], device\u001b[38;5;241m=\u001b[39m\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mcuda\u001b[39m\u001b[38;5;124m'\u001b[39m)\n\u001b[1;32m     69\u001b[0m positives_lengths \u001b[38;5;241m=\u001b[39m torch\u001b[38;5;241m.\u001b[39mas_tensor([positive\u001b[38;5;241m.\u001b[39mshape[\u001b[38;5;241m1\u001b[39m] \u001b[38;5;28;01mfor\u001b[39;00m positive \u001b[38;5;129;01min\u001b[39;00m positives], device\u001b[38;5;241m=\u001b[39m\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mcuda\u001b[39m\u001b[38;5;124m'\u001b[39m)\n",
      "\u001b[0;31mKeyboardInterrupt\u001b[0m: "
     ]
    }
   ],
   "source": [
    "import wandb\n",
    "from torch.utils.data import DataLoader\n",
    "from torch.optim import AdamW\n",
    "import torch.nn as nn\n",
    "from tqdm import tqdm\n",
    "\n",
    "\n",
    "wandb.init(project='original_style_metric_training_nsynth', config={\n",
    "    \"learning_rate\": learning_rate,\n",
    "    \"batch_size\": batch_size,\n",
    "    \"epochs\": no_of_epochs,\n",
    "    \"train_audios_path\": train_audios_folder,\n",
    "    \"valid_audios_path\": valid_audios_folder,\n",
    "    \"output_path\": output_path\n",
    "})\n",
    "\n",
    "# make sure the output directory exists\n",
    "if not os.path.exists(wandb.config.output_path):\n",
    "    os.makedirs(wandb.config.output_path)\n",
    "\n",
    "config = wandb.config\n",
    "\n",
    "train_dataset = NSynthDataset(cfg, base_folder=config.train_audios_path)\n",
    "valid_dataset = NSynthDataset(cfg, base_folder=config.valid_audios_path)\n",
    "\n",
    "train_sampler = PairSampler(train_dataset, config.batch_size)\n",
    "valid_sampler = PairSampler(valid_dataset, config.batch_size)\n",
    "\n",
    "train_loader = DataLoader(\n",
    "    train_dataset,\n",
    "    num_workers=8,\n",
    "    batch_sampler=train_sampler,\n",
    ")\n",
    "valid_loader = DataLoader(\n",
    "    valid_dataset,\n",
    "    num_workers=4,\n",
    "    batch_sampler=valid_sampler,\n",
    ")\n",
    "\n",
    "bilinear_similarity = BilinearSimilarity(cfg['model']['style_encoder_rnn']['hidden_size'].get())\n",
    "bilinear_similarity.cuda()\n",
    "bilinear_similarity.train()\n",
    "\n",
    "style_encoder.cuda()\n",
    "style_encoder.train()\n",
    "\n",
    "optimizer = AdamW([{'params': style_encoder.parameters()}, {'params': bilinear_similarity.parameters()}], \n",
    "                  lr=config.learning_rate)\n",
    "cross_entropy = nn.CrossEntropyLoss()\n",
    "\n",
    "step = 0\n",
    "for epoch in range(config.epochs):\n",
    "    style_encoder.train()\n",
    "    bilinear_similarity.train()\n",
    "    \n",
    "    # Training loop\n",
    "    for ix, batch in tqdm(enumerate(train_loader)):\n",
    "        if ix == 1000:\n",
    "            break\n",
    "        \n",
    "        step += 1\n",
    "        positives = batch[0::2]\n",
    "        anchors = batch[1::2]\n",
    "        \n",
    "        n_batch = anchors.shape[0]\n",
    "        anchors = anchors.cuda()\n",
    "        positives = positives.cuda()\n",
    "        anchors_lengths = torch.as_tensor([anchor.shape[1] for anchor in anchors], device='cuda')\n",
    "        positives_lengths = torch.as_tensor([positive.shape[1] for positive in positives], device='cuda')\n",
    "        optimizer.zero_grad()\n",
    "        \n",
    "        y_anchors, _ = style_encoder(anchors, anchors_lengths)\n",
    "        y_positives, _ = style_encoder(positives, positives_lengths)\n",
    "        \n",
    "        similarities = bilinear_similarity(y_anchors, y_positives)\n",
    "        loss = cross_entropy(similarities, torch.arange(n_batch).cuda())\n",
    "\n",
    "        loss.backward()\n",
    "        optimizer.step()\n",
    "        \n",
    "        wandb.log({'train_loss': loss.item()}, step=step)\n",
    "    \n",
    "    # Validation loop\n",
    "    style_encoder.eval()\n",
    "    bilinear_similarity.eval()\n",
    "    epoch_val_loss = 0.0\n",
    "    \n",
    "    with torch.no_grad():\n",
    "        for ix, batch in tqdm(enumerate(valid_loader)):\n",
    "            positives = batch[0::2]\n",
    "            anchors = batch[1::2]\n",
    "            \n",
    "            n_batch = anchors.shape[0]\n",
    "            anchors = anchors.cuda()\n",
    "            positives = positives.cuda()\n",
    "            anchors_lengths = torch.as_tensor([anchor.shape[1] for anchor in anchors], device='cuda')\n",
    "            positives_lengths = torch.as_tensor([positive.shape[1] for positive in positives], device='cuda')\n",
    "            \n",
    "            y_anchors, _ = style_encoder(anchors, anchors_lengths)\n",
    "            y_positives, _ = style_encoder(positives, positives_lengths)\n",
    "\n",
    "            similarities = bilinear_similarity(y_anchors, y_positives)\n",
    "            loss = cross_entropy(similarities, torch.arange(n_batch).cuda())\n",
    "\n",
    "            epoch_val_loss += loss.item()\n",
    "\n",
    "    wandb.log({'val_loss': epoch_val_loss / len(valid_loader)}, step=step)\n",
    "    \n",
    "    latest_checkpoint_path = os.path.join(config.output_path, 'style_encoder_latest.pth')\n",
    "    torch.save(style_encoder.state_dict(), latest_checkpoint_path)\n",
    "    torch.save(bilinear_similarity.state_dict(), os.path.join(config.output_path, 'bilinear_similarity_latest.pth'))\n",
    "    wandb.save(latest_checkpoint_path)\n",
    "\n",
    "# Save the model checkpoint\n",
    "torch.save(style_encoder.state_dict(), 'style_encoder.pth')\n",
    "wandb.save('style_encoder.pth')\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "17f8d0cd-a9b8-4011-80b0-4ba174a82324",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "conda",
   "language": "python",
   "name": "conda"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.10"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
